version: "3.8"
services:
  gomock_issue_varargs:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/src:cached
      - /var/run/docker.sock:/var/run/docker.sock
    user: vscode
    # Ensure the container runs forever
    command: "-f /dev/null"
    entrypoint: /usr/bin/tail
    tty: true
